# Generated by Django 3.2.3 on 2021-05-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_date_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='crator',
            new_name='user',
        ),
    ]
